Check trackable-field, when training is saved
cgrabmann/jugger-tracker pull request #37
Opened 2019-03-10 14:25 UTC by DerDodo

2019-03-10 15:21 UTC, cgrabmann requested changes

2019-03-10 15:21 UTC, cgrabmann commented on src/main/frontend/js/vue/component/Training.vue
> +            for (let user: User of this.trainingState.editTraining.participants) {
die for schleife könnte mit einem `Array.some()` call ersetzt werden.

2019-03-10 15:21 UTC, cgrabmann commented on src/main/java/at/jugger/tracker/controller/TrainingController.java
> +    private void checkTrackableFieldAndThrow(Training training) {
In meinen Augen sollte das nicht der Controller handeln sonder der Service.

2019-03-10 15:21 UTC, cgrabmann commented on src/main/frontend/js/vue/component/Training.vue
> +                                <div :class="participant.item.trackable ? 'trackable' : 'not-trackable'">
Können wir Leute die nicht getracked werden wollen, nicht einfach nicht auswählbar machen?
Die v-select Component hat eine item-disabled Property mit der das nach meinem Verständnis funktionieren sollte.

2019-03-10 16:15 UTC, DerDodo commented on src/main/frontend/js/vue/component/Training.vue
> +                                <div :class="participant.item.trackable ? 'trackable' : 'not-trackable'">
Hätts versucht, aber ich hab keine Möglichkeit gefunden, wies mim template geht. Hab etwa eine Stunde rumprobiert.

2019-03-11 06:10 UTC, cgrabmann submitted a review, later dismissed

2019-03-12 12:31 UTC, cgrabmann approved these changes

2019-03-12 12:31 UTC, merged